name: Lighthouse CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://phamhoa205.github.io/devops-lab1-portfolio/
            https://phamhoa205.github.io/devops-lab1-portfolio/about.html
            https://phamhoa205.github.io/devops-lab1-portfolio/contact.html
          configPath: ./lighthouserc.json
          uploadArtifacts: true